### ISSUE TITLE
No linting for ruby in erb view files?

### ISSUE THREAD

**Issue by tamaloa** [rails/rubocop-rails-omakase#21]
I am suprised there is no linting enabled for **ruby** code in erb files.

Is the suggested approach to use https://github.com/r7kamura/rubocop-erb and
```
require:
  - rubocop-erb
```

in `.rubocop.yml`?

**Comment by Earlopain** [comment]
`rubocop-erb` is one option. There is also [erb_lint](https://github.com/Shopify/erb_lint) which in addition to just checking the ruby code does some more broad checks, like looking for unsafe interpolation in javascript contexts ([link](https://github.com/Shopify/erb_lint?tab=readme-ov-file#erbsafety)), among other things.

Personally I prefer `rubocop-erb` since it is just a normal rubocop extension and integrates well in the normal workflow without an extra tool. It is more limited though.

**Comment by tamaloa** [comment]
Thanks for the clarification :+1:
